travis:
  secure:
    BINSTAR_TOKEN: aGs0DE5SaVV88Ek9/W7Wqq956RgddeD6OkY3I6lFlE3cgr2IV41QcBbS8zmGy0WlTM0KNpE+w4/HOeyKk9EiTXqQCfbsZ2BCM/QeOwx3uSw8uN0w8TN0NC2idyg2BspSVjH/Gf4jW5Exdg1enUgIb3HZPbG2z+0AsysQBSJRf0wzZs5fMkGHjWPKF8X3iqE/Mf9JiaMz3d6AR5NulluzOwxBrjEBVMaa/ZXJn+YEVX6eiFY0tXTplrxgVWtNr1KSJL0ULpEfnRNtyUXXPUrYyiLUJ4jvPieKu9bzR+Ix7Sa+Q45eOTS61HfdWwK8wTPguPraTr7zUy3twPYTQTbfbcDfFaKIwScnv56XSYHUVfgPVvaiD11h4mF7p6hoDfab7wGe0i7jmVXP+C88o6cMk/hMNRMdu71jvXRmoIO2UAQki8PRFYo647f4N1RwrNhqCTEmsQ3hOY926NnIvGgOmpCTtarfUezTCGmBnJtMqujBfszoNbGxDf0P1x9nZtMGvbmK3vZmxzKu+9VVQB6bMr+H2x1vG7OJmno+8RiwbYCU0i4XBbqbK5hWB8GVet8nI41FisSQH58uvq13dhGy31d2LZDgJzbApwCjAr0wuOxfAMzQzH+D/1a1yD6dUxb7g7oQZIQfyrV7fBE6uz9jhczUCos5MR/sXiRWv0+6ark=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
